### ISSUE TITLE
failing to run demo code

### ISSUE THREAD

**Issue by lukas-runge** [eliassjogreen/deno_webview#7]
Hello @eliassjogreen,

I recently started tooling around with deno and also tried your webview module. Sadly I did not get it to work on either windows nor ubuntu.

I just ran the demo code:
```Typescript
import { WebView } from "https://deno.land/x/webview/mod.ts";

const webview1 = new WebView({
    title: "Multiple deno_webview example",
    url: `data:text/html,
    <html>
    <body>
      <h1>1</h1>
    </body>
    </html>
    `,
    width: 800,
    height: 600,
    resizable: true,
    debug: true,
    frameless: false,
});

const webview2 = new WebView({
    title: "Multiple deno_webview example",
    url: `data:text/html,
    <html>
    <body>
      <h1>2</h1>
    </body>
    </html>
    `,
    width: 800,
    height: 600,
    resizable: true,
    debug: true,
    frameless: false,
});

await Promise.all([webview1.run(), webview2.run()]);
```

Here is my error-log:
```
lukas@Yobuntu:/media/sdaten_ext4/code/scanSort$ deno run -A gui.ts
Compile file:///media/sdaten_ext4/code/scanSort/gui.ts
Download https://deno.land/x/webview/mod.ts
Download https://deno.land/x/webview/plugin.ts
Download https://deno.land/x/plugin_prepare@v0.3.1/mod.ts
Download https://deno.land/std/fs/exists.ts
Download https://deno.land/std/log/mod.ts
Download https://deno.land/std/path/mod.ts
Download https://deno.land/x/checksum@1.2.0/mod.ts
Download https://deno.land/std/log/logger.ts
Download https://deno.land/std/log/handlers.ts
Download https://deno.land/std/testing/asserts.ts
Download https://deno.land/std/log/levels.ts
Download https://deno.land/std/log/levels.ts
Download https://deno.land/std/fmt/colors.ts
Download https://deno.land/std/testing/diff.ts
Download https://deno.land/std/path/win32.ts
Download https://deno.land/std/path/posix.ts
Download https://deno.land/std/path/common.ts
Download https://deno.land/std/path/separator.ts
Download https://deno.land/std/path/interface.ts
Download https://deno.land/std/path/glob.ts
Download https://deno.land/std/path/_constants.ts
Download https://deno.land/std/path/_util.ts
Download https://deno.land/std/path/_globrex.ts
Download https://deno.land/x/checksum@1.2.0/hash.ts
Download https://deno.land/x/checksum@1.2.0/sha1.ts
Download https://deno.land/x/checksum@1.2.0/md5.ts
error: TS2694 [ERROR]: Namespace 'Deno' has no exported member 'OperatingSystem'.
const PLUGIN_SUFFIX_MAP: { [os in Deno.OperatingSystem]: string } = {
                                       ~~~~~~~~~~~~~~~
    at https://deno.land/x/plugin_prepare@v0.3.1/mod.ts:9:40

TS7053 [ERROR]: Element implicitly has an 'any' type because expression of type '"darwin" | "linux" | "windows"' can't be used to index type '{ mac?: string | undefined; linux?: string | undefined; win?: string | undefined; }'.
  Property 'darwin' does not exist on type '{ mac?: string | undefined; linux?: string | undefined; win?: string | undefined; }'.
  const remoteUrl = urls[os];
                    ~~~~~~~~
    at https://deno.land/x/plugin_prepare@v0.3.1/mod.ts:35:21

TS2339 [ERROR]: Property 'openPlugin' does not exist on type 'typeof Deno'.
  return Deno.openPlugin(localPath);
              ~~~~~~~~~~
    at https://deno.land/x/plugin_prepare@v0.3.1/mod.ts:58:15

TS2349 [ERROR]: This expression is not callable.
  Type '{ get(key: string): string | undefined; set(key: string, value: string): void; toObject(): { [index: string]: string; }; }' has no call signatures.
const DEV = Deno.env("DEV");
                 ~~~
    at https://deno.land/x/webview/plugin.ts:3:18

TS2349 [ERROR]: This expression is not callable.
  Type '{ get(key: string): string | undefined; set(key: string, value: string): void; toObject(): { [index: string]: string; }; }' has no call signatures.
const MSHTML = Deno.env("MSHTML");
                    ~~~
    at https://deno.land/x/webview/plugin.ts:5:21

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'PluginOp'.
  op: Deno.PluginOp,
           ~~~~~~~~
    at https://deno.land/x/webview/plugin.ts:25:12

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'PluginOp'.
  op: Deno.PluginOp,
           ~~~~~~~~
    at https://deno.land/x/webview/plugin.ts:38:12

TS7006 [ERROR]: Parameter 'raw' implicitly has an 'any' type.
    op.setAsyncHandler((raw) => {
                        ~~~
    at https://deno.land/x/webview/plugin.ts:42:25

Found 8 errors.
lukas@Yobuntu:/media/sdaten_ext4/code/scanSort$ 
```

Hope there is a solution. Thanks already!
Kind regards
@lukas-runge

**Comment by eliassjogreen** [comment]
The latest supported version of deno is `v0.41.0` due to recent changes to the deno plugin system.

**Comment by lukas-runge** [comment]
![image](https://user-images.githubusercontent.com/21328241/81561674-d74f5e80-9393-11ea-894a-9248478191a7.png)
