### ISSUE TITLE
Can't run an example

### ISSUE THREAD

**Issue by sgtpep** [eliassjogreen/deno_webview#8]
Sorry, I'm new to deno and couldn't run an example to try it.

```
deno --version
deno 1.0.0-rc3
v8 8.4.300
typescript 3.8.3
```

If I run `deno -A https://deno.land/x/webview/examples/multiple.ts`, it fails with:
```
error: Found argument '-A' which wasn't expected, or isn't valid in this context

USAGE:
    deno [OPTIONS] [SUBCOMMAND]

For more information try --help
```

If I run `deno run -A https://deno.land/x/webview/examples/multiple.ts`, if fails with:
```
Compile https://deno.land/x/webview/examples/multiple.ts
error: TS2694 [ERROR]: Namespace 'Deno' has no exported member 'OperatingSystem'.
const PLUGIN_SUFFIX_MAP: { [os in Deno.OperatingSystem]: string } = {
                                       ~~~~~~~~~~~~~~~
    at https://deno.land/x/plugin_prepare@v0.3.1/mod.ts:9:40

TS7053 [ERROR]: Element implicitly has an 'any' type because expression of type '"darwin" | "linux" | "windows"' can't be used to index type '{ mac?: string | undefined; linux?: string | undefined; win?: string | undefined; }'.
  Property 'darwin' does not exist on type '{ mac?: string | undefined; linux?: string | undefined; win?: string | undefined; }'.
  const remoteUrl = urls[os];
                    ~~~~~~~~
    at https://deno.land/x/plugin_prepare@v0.3.1/mod.ts:35:21

TS2339 [ERROR]: Property 'openPlugin' does not exist on type 'typeof Deno'.
  return Deno.openPlugin(localPath);
              ~~~~~~~~~~
    at https://deno.land/x/plugin_prepare@v0.3.1/mod.ts:58:15

TS2349 [ERROR]: This expression is not callable.
  Type '{ get(key: string): string | undefined; set(key: string, value: string): void; toObject(): { [index: string]: string; }; }' has no call signatures.
const DEV = Deno.env("DEV");
                 ~~~
    at https://deno.land/x/webview/plugin.ts:3:18

TS2349 [ERROR]: This expression is not callable.
  Type '{ get(key: string): string | undefined; set(key: string, value: string): void; toObject(): { [index: string]: string; }; }' has no call signatures.
const MSHTML = Deno.env("MSHTML");
                    ~~~
    at https://deno.land/x/webview/plugin.ts:5:21

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'PluginOp'.
  op: Deno.PluginOp,
           ~~~~~~~~
    at https://deno.land/x/webview/plugin.ts:25:12

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'PluginOp'.
  op: Deno.PluginOp,
           ~~~~~~~~
    at https://deno.land/x/webview/plugin.ts:38:12

TS7006 [ERROR]: Parameter 'raw' implicitly has an 'any' type.
    op.setAsyncHandler((raw) => {
                        ~~~
    at https://deno.land/x/webview/plugin.ts:42:25

Found 8 errors.
```

**Comment by eliassjogreen** [comment]
Same as #7. Will soon be updated to latest release
